"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from laboratory import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _FanMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FanModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FanMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    AUTO: _FanMode.ValueType  # 0
    ECO: _FanMode.ValueType  # 1
    FAST: _FanMode.ValueType  # 2

class FanMode(_FanMode, metaclass=_FanModeEnumTypeWrapper): ...

AUTO: FanMode.ValueType  # 0
ECO: FanMode.ValueType  # 1
FAST: FanMode.ValueType  # 2
Global___FanMode: _TypeAlias = FanMode  # noqa: Y015

@_typing.final
class BasicACData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___BasicACData: _TypeAlias = BasicACData  # noqa: Y015

@_typing.final
class AdvancedACData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FAN_MODE_FIELD_NUMBER: _builtins.int
    CURRENT_HUMIDITY_FIELD_NUMBER: _builtins.int
    TARGET_HUMIDITY_FIELD_NUMBER: _builtins.int
    fan_mode: Global___FanMode.ValueType
    current_humidity: _builtins.int
    target_humidity: _builtins.int
    def __init__(
        self,
        *,
        fan_mode: Global___FanMode.ValueType = ...,
        current_humidity: _builtins.int = ...,
        target_humidity: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["current_humidity", b"current_humidity", "fan_mode", b"fan_mode", "target_humidity", b"target_humidity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AdvancedACData: _TypeAlias = AdvancedACData  # noqa: Y015

@_typing.final
class ACStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    IS_ON_FIELD_NUMBER: _builtins.int
    CURRENT_TEMP_FIELD_NUMBER: _builtins.int
    TARGET_TEMP_FIELD_NUMBER: _builtins.int
    BASIC_FIELD_NUMBER: _builtins.int
    ADVANCED_FIELD_NUMBER: _builtins.int
    is_on: _builtins.bool
    current_temp: _builtins.int
    target_temp: _builtins.int
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    @_builtins.property
    def basic(self) -> Global___BasicACData: ...
    @_builtins.property
    def advanced(self) -> Global___AdvancedACData: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        is_on: _builtins.bool = ...,
        current_temp: _builtins.int = ...,
        target_temp: _builtins.int = ...,
        basic: Global___BasicACData | None = ...,
        advanced: Global___AdvancedACData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["advanced", b"advanced", "basic", b"basic", "id", b"id", "type_detalis", b"type_detalis"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["advanced", b"advanced", "basic", b"basic", "current_temp", b"current_temp", "id", b"id", "is_on", b"is_on", "target_temp", b"target_temp", "type_detalis", b"type_detalis"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_type_detalis: _TypeAlias = _typing.Literal["basic", "advanced"]  # noqa: Y015
    _WhichOneofArgType_type_detalis: _TypeAlias = _typing.Literal["type_detalis", b"type_detalis"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type_detalis) -> _WhichOneofReturnType_type_detalis | None: ...

Global___ACStatus: _TypeAlias = ACStatus  # noqa: Y015

@_typing.final
class SetACTempRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TARGET_TEMP_FIELD_NUMBER: _builtins.int
    target_temp: _builtins.int
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        target_temp: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "target_temp", b"target_temp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetACTempRequest: _TypeAlias = SetACTempRequest  # noqa: Y015

@_typing.final
class SetACFanRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    FAN_MODE_FIELD_NUMBER: _builtins.int
    fan_mode: Global___FanMode.ValueType
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        fan_mode: Global___FanMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fan_mode", b"fan_mode", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetACFanRequest: _TypeAlias = SetACFanRequest  # noqa: Y015

@_typing.final
class SetACHumidityRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TARGET_HUMIDITY_FIELD_NUMBER: _builtins.int
    target_humidity: _builtins.int
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        target_humidity: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "target_humidity", b"target_humidity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetACHumidityRequest: _TypeAlias = SetACHumidityRequest  # noqa: Y015
