# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from laboratory import air_conditioner_pb2 as laboratory_dot_air__conditioner__pb2
from laboratory import common_pb2 as laboratory_dot_common__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in laboratory/air_conditioner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ACServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetACStatus = channel.unary_unary(
                '/laboratory.ACService/GetACStatus',
                request_serializer=laboratory_dot_common__pb2.DeviceID.SerializeToString,
                response_deserializer=laboratory_dot_air__conditioner__pb2.ACStatus.FromString,
                _registered_method=True)
        self.EnableAC = channel.unary_unary(
                '/laboratory.ACService/EnableAC',
                request_serializer=laboratory_dot_common__pb2.DeviceID.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DisableAC = channel.unary_unary(
                '/laboratory.ACService/DisableAC',
                request_serializer=laboratory_dot_common__pb2.DeviceID.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetACTemp = channel.unary_unary(
                '/laboratory.ACService/SetACTemp',
                request_serializer=laboratory_dot_air__conditioner__pb2.SetACTempRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetACFan = channel.unary_unary(
                '/laboratory.ACService/SetACFan',
                request_serializer=laboratory_dot_air__conditioner__pb2.SetACFanRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetACHumidity = channel.unary_unary(
                '/laboratory.ACService/SetACHumidity',
                request_serializer=laboratory_dot_air__conditioner__pb2.SetACHumidityRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ACServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetACStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableAC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableAC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetACTemp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetACFan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetACHumidity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ACServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetACStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetACStatus,
                    request_deserializer=laboratory_dot_common__pb2.DeviceID.FromString,
                    response_serializer=laboratory_dot_air__conditioner__pb2.ACStatus.SerializeToString,
            ),
            'EnableAC': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableAC,
                    request_deserializer=laboratory_dot_common__pb2.DeviceID.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DisableAC': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableAC,
                    request_deserializer=laboratory_dot_common__pb2.DeviceID.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetACTemp': grpc.unary_unary_rpc_method_handler(
                    servicer.SetACTemp,
                    request_deserializer=laboratory_dot_air__conditioner__pb2.SetACTempRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetACFan': grpc.unary_unary_rpc_method_handler(
                    servicer.SetACFan,
                    request_deserializer=laboratory_dot_air__conditioner__pb2.SetACFanRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetACHumidity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetACHumidity,
                    request_deserializer=laboratory_dot_air__conditioner__pb2.SetACHumidityRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'laboratory.ACService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('laboratory.ACService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ACService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetACStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.ACService/GetACStatus',
            laboratory_dot_common__pb2.DeviceID.SerializeToString,
            laboratory_dot_air__conditioner__pb2.ACStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableAC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.ACService/EnableAC',
            laboratory_dot_common__pb2.DeviceID.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableAC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.ACService/DisableAC',
            laboratory_dot_common__pb2.DeviceID.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetACTemp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.ACService/SetACTemp',
            laboratory_dot_air__conditioner__pb2.SetACTempRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetACFan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.ACService/SetACFan',
            laboratory_dot_air__conditioner__pb2.SetACFanRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetACHumidity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.ACService/SetACHumidity',
            laboratory_dot_air__conditioner__pb2.SetACHumidityRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
