# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: laboratory/air_conditioner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'laboratory/air_conditioner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from laboratory import common_pb2 as laboratory_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n laboratory/air_conditioner.proto\x12\nlaboratory\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17laboratory/common.proto\"\r\n\x0b\x42\x61sicACData\"j\n\x0e\x41\x64vancedACData\x12%\n\x08\x66\x61n_mode\x18\x01 \x01(\x0e\x32\x13.laboratory.FanMode\x12\x18\n\x10\x63urrent_humidity\x18\x02 \x01(\x05\x12\x17\n\x0ftarget_humidity\x18\x03 \x01(\x05\"\xd0\x01\n\x08\x41\x43Status\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12\r\n\x05is_on\x18\x02 \x01(\x08\x12\x14\n\x0c\x63urrent_temp\x18\x03 \x01(\x05\x12\x13\n\x0btarget_temp\x18\x04 \x01(\x05\x12(\n\x05\x62\x61sic\x18\x05 \x01(\x0b\x32\x17.laboratory.BasicACDataH\x00\x12.\n\x08\x61\x64vanced\x18\x06 \x01(\x0b\x32\x1a.laboratory.AdvancedACDataH\x00\x42\x0e\n\x0ctype_detalis\"I\n\x10SetACTempRequest\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12\x13\n\x0btarget_temp\x18\x02 \x01(\x05\"Z\n\x0fSetACFanRequest\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12%\n\x08\x66\x61n_mode\x18\x02 \x01(\x0e\x32\x13.laboratory.FanMode\"Q\n\x14SetACHumidityRequest\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12\x17\n\x0ftarget_humidity\x18\x02 \x01(\x05*&\n\x07\x46\x61nMode\x12\x08\n\x04\x41UTO\x10\x00\x12\x07\n\x03\x45\x43O\x10\x01\x12\x08\n\x04\x46\x41ST\x10\x02\x32\x8a\x03\n\tACService\x12\x39\n\x0bGetACStatus\x12\x14.laboratory.DeviceID\x1a\x14.laboratory.ACStatus\x12\x38\n\x08\x45nableAC\x12\x14.laboratory.DeviceID\x1a\x16.google.protobuf.Empty\x12\x39\n\tDisableAC\x12\x14.laboratory.DeviceID\x1a\x16.google.protobuf.Empty\x12\x41\n\tSetACTemp\x12\x1c.laboratory.SetACTempRequest\x1a\x16.google.protobuf.Empty\x12?\n\x08SetACFan\x12\x1b.laboratory.SetACFanRequest\x1a\x16.google.protobuf.Empty\x12I\n\rSetACHumidity\x12 .laboratory.SetACHumidityRequest\x1a\x16.google.protobuf.EmptyB\x17\n\x13org.mpus.laboratoryP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'laboratory.air_conditioner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023org.mpus.laboratoryP\001'
  _globals['_FANMODE']._serialized_start=686
  _globals['_FANMODE']._serialized_end=724
  _globals['_BASICACDATA']._serialized_start=102
  _globals['_BASICACDATA']._serialized_end=115
  _globals['_ADVANCEDACDATA']._serialized_start=117
  _globals['_ADVANCEDACDATA']._serialized_end=223
  _globals['_ACSTATUS']._serialized_start=226
  _globals['_ACSTATUS']._serialized_end=434
  _globals['_SETACTEMPREQUEST']._serialized_start=436
  _globals['_SETACTEMPREQUEST']._serialized_end=509
  _globals['_SETACFANREQUEST']._serialized_start=511
  _globals['_SETACFANREQUEST']._serialized_end=601
  _globals['_SETACHUMIDITYREQUEST']._serialized_start=603
  _globals['_SETACHUMIDITYREQUEST']._serialized_end=684
  _globals['_ACSERVICE']._serialized_start=727
  _globals['_ACSERVICE']._serialized_end=1121
# @@protoc_insertion_point(module_scope)
