# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: laboratory/camera.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'laboratory/camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from laboratory import common_pb2 as laboratory_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17laboratory/camera.proto\x12\nlaboratory\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17laboratory/common.proto\"h\n\x0c\x43\x61meraStatus\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12\r\n\x05is_on\x18\x02 \x01(\x08\x12\x0b\n\x03pan\x18\x03 \x01(\x05\x12\x0c\n\x04tilt\x18\x04 \x01(\x05\x12\x0c\n\x04zoom\x18\x05 \x01(\x05\"D\n\x13SetCameraPanRequest\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12\x0b\n\x03pan\x18\x02 \x01(\x05\"F\n\x14SetCameraTiltRequest\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12\x0c\n\x04tilt\x18\x02 \x01(\x05\"F\n\x14SetCameraZoomRequest\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12\x0c\n\x04zoom\x18\x02 \x01(\x05\x32\xae\x03\n\rCameraService\x12\x41\n\x0fGetCameraStatus\x12\x14.laboratory.DeviceID\x1a\x18.laboratory.CameraStatus\x12<\n\x0c\x45nableCamera\x12\x14.laboratory.DeviceID\x1a\x16.google.protobuf.Empty\x12=\n\rDisableCamera\x12\x14.laboratory.DeviceID\x1a\x16.google.protobuf.Empty\x12G\n\x0cSetCameraPan\x12\x1f.laboratory.SetCameraPanRequest\x1a\x16.google.protobuf.Empty\x12I\n\rSetCameraTilt\x12 .laboratory.SetCameraTiltRequest\x1a\x16.google.protobuf.Empty\x12I\n\rSetCameraZoom\x12 .laboratory.SetCameraZoomRequest\x1a\x16.google.protobuf.EmptyB\x17\n\x13org.mpus.laboratoryP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'laboratory.camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023org.mpus.laboratoryP\001'
  _globals['_CAMERASTATUS']._serialized_start=93
  _globals['_CAMERASTATUS']._serialized_end=197
  _globals['_SETCAMERAPANREQUEST']._serialized_start=199
  _globals['_SETCAMERAPANREQUEST']._serialized_end=267
  _globals['_SETCAMERATILTREQUEST']._serialized_start=269
  _globals['_SETCAMERATILTREQUEST']._serialized_end=339
  _globals['_SETCAMERAZOOMREQUEST']._serialized_start=341
  _globals['_SETCAMERAZOOMREQUEST']._serialized_end=411
  _globals['_CAMERASERVICE']._serialized_start=414
  _globals['_CAMERASERVICE']._serialized_end=844
# @@protoc_insertion_point(module_scope)
