"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from laboratory import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CameraStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    IS_ON_FIELD_NUMBER: _builtins.int
    PAN_FIELD_NUMBER: _builtins.int
    TILT_FIELD_NUMBER: _builtins.int
    ZOOM_FIELD_NUMBER: _builtins.int
    is_on: _builtins.bool
    pan: _builtins.int
    tilt: _builtins.int
    zoom: _builtins.int
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        is_on: _builtins.bool = ...,
        pan: _builtins.int = ...,
        tilt: _builtins.int = ...,
        zoom: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "is_on", b"is_on", "pan", b"pan", "tilt", b"tilt", "zoom", b"zoom"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CameraStatus: _TypeAlias = CameraStatus  # noqa: Y015

@_typing.final
class SetCameraPanRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    PAN_FIELD_NUMBER: _builtins.int
    pan: _builtins.int
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        pan: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "pan", b"pan"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetCameraPanRequest: _TypeAlias = SetCameraPanRequest  # noqa: Y015

@_typing.final
class SetCameraTiltRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TILT_FIELD_NUMBER: _builtins.int
    tilt: _builtins.int
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        tilt: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "tilt", b"tilt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetCameraTiltRequest: _TypeAlias = SetCameraTiltRequest  # noqa: Y015

@_typing.final
class SetCameraZoomRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    ZOOM_FIELD_NUMBER: _builtins.int
    zoom: _builtins.int
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        zoom: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "zoom", b"zoom"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetCameraZoomRequest: _TypeAlias = SetCameraZoomRequest  # noqa: Y015
