# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: laboratory/irrigation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'laboratory/irrigation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from laboratory import common_pb2 as laboratory_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blaboratory/irrigation.proto\x12\nlaboratory\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17laboratory/common.proto\")\n\x13WaterIrrigationData\x12\x12\n\nwater_flow\x18\x01 \x01(\x05\"4\n\x18\x46\x65rtilizerIrrigationData\x12\x18\n\x10\x66\x65rtilizer_ratio\x18\x01 \x01(\x05\"\xf1\x01\n\x10IrrigationStatus\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12\r\n\x05is_on\x18\x02 \x01(\x08\x12$\n\x05light\x18\x03 \x01(\x0e\x32\x15.laboratory.LightMode\x12\x35\n\nwater_type\x18\x04 \x01(\x0b\x32\x1f.laboratory.WaterIrrigationDataH\x00\x12?\n\x0f\x66\x65rtilizer_type\x18\x05 \x01(\x0b\x32$.laboratory.FertilizerIrrigationDataH\x00\x42\x0e\n\x0ctype_detalis\"]\n\x13SetLightModeRequest\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12$\n\x05light\x18\x02 \x01(\x0e\x32\x15.laboratory.LightMode\"K\n\x13SetWaterFlowRequest\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12\x12\n\nwater_flow\x18\x02 \x01(\x05\"W\n\x19SetFertilizerRatioRequest\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.laboratory.DeviceID\x12\x18\n\x10\x66\x65rtilizer_ratio\x18\x02 \x01(\x05*9\n\tLightMode\x12\x0c\n\x08NO_LIGHT\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\x08\n\x04HIGH\x10\x02\x12\x0b\n\x07\x45XTREME\x10\x03\x32\xca\x03\n\x11IrrigationService\x12I\n\x13GetIrrigationStatus\x12\x14.laboratory.DeviceID\x1a\x1c.laboratory.IrrigationStatus\x12@\n\x10\x45nableIrrigation\x12\x14.laboratory.DeviceID\x1a\x16.google.protobuf.Empty\x12\x41\n\x11\x44isableIrrigation\x12\x14.laboratory.DeviceID\x1a\x16.google.protobuf.Empty\x12G\n\x0cSetLightMode\x12\x1f.laboratory.SetLightModeRequest\x1a\x16.google.protobuf.Empty\x12G\n\x0cSetWaterFlow\x12\x1f.laboratory.SetWaterFlowRequest\x1a\x16.google.protobuf.Empty\x12S\n\x12SetFertilizerRatio\x12%.laboratory.SetFertilizerRatioRequest\x1a\x16.google.protobuf.EmptyB\x17\n\x13org.mpus.laboratoryP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'laboratory.irrigation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023org.mpus.laboratoryP\001'
  _globals['_LIGHTMODE']._serialized_start=699
  _globals['_LIGHTMODE']._serialized_end=756
  _globals['_WATERIRRIGATIONDATA']._serialized_start=97
  _globals['_WATERIRRIGATIONDATA']._serialized_end=138
  _globals['_FERTILIZERIRRIGATIONDATA']._serialized_start=140
  _globals['_FERTILIZERIRRIGATIONDATA']._serialized_end=192
  _globals['_IRRIGATIONSTATUS']._serialized_start=195
  _globals['_IRRIGATIONSTATUS']._serialized_end=436
  _globals['_SETLIGHTMODEREQUEST']._serialized_start=438
  _globals['_SETLIGHTMODEREQUEST']._serialized_end=531
  _globals['_SETWATERFLOWREQUEST']._serialized_start=533
  _globals['_SETWATERFLOWREQUEST']._serialized_end=608
  _globals['_SETFERTILIZERRATIOREQUEST']._serialized_start=610
  _globals['_SETFERTILIZERRATIOREQUEST']._serialized_end=697
  _globals['_IRRIGATIONSERVICE']._serialized_start=759
  _globals['_IRRIGATIONSERVICE']._serialized_end=1217
# @@protoc_insertion_point(module_scope)
