"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from laboratory import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _LightMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LightModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LightMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NO_LIGHT: _LightMode.ValueType  # 0
    LOW: _LightMode.ValueType  # 1
    HIGH: _LightMode.ValueType  # 2
    EXTREME: _LightMode.ValueType  # 3

class LightMode(_LightMode, metaclass=_LightModeEnumTypeWrapper): ...

NO_LIGHT: LightMode.ValueType  # 0
LOW: LightMode.ValueType  # 1
HIGH: LightMode.ValueType  # 2
EXTREME: LightMode.ValueType  # 3
Global___LightMode: _TypeAlias = LightMode  # noqa: Y015

@_typing.final
class WaterIrrigationData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WATER_FLOW_FIELD_NUMBER: _builtins.int
    water_flow: _builtins.int
    def __init__(
        self,
        *,
        water_flow: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["water_flow", b"water_flow"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WaterIrrigationData: _TypeAlias = WaterIrrigationData  # noqa: Y015

@_typing.final
class FertilizerIrrigationData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FERTILIZER_RATIO_FIELD_NUMBER: _builtins.int
    fertilizer_ratio: _builtins.int
    def __init__(
        self,
        *,
        fertilizer_ratio: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fertilizer_ratio", b"fertilizer_ratio"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FertilizerIrrigationData: _TypeAlias = FertilizerIrrigationData  # noqa: Y015

@_typing.final
class IrrigationStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    IS_ON_FIELD_NUMBER: _builtins.int
    LIGHT_FIELD_NUMBER: _builtins.int
    WATER_TYPE_FIELD_NUMBER: _builtins.int
    FERTILIZER_TYPE_FIELD_NUMBER: _builtins.int
    is_on: _builtins.bool
    light: Global___LightMode.ValueType
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    @_builtins.property
    def water_type(self) -> Global___WaterIrrigationData: ...
    @_builtins.property
    def fertilizer_type(self) -> Global___FertilizerIrrigationData: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        is_on: _builtins.bool = ...,
        light: Global___LightMode.ValueType = ...,
        water_type: Global___WaterIrrigationData | None = ...,
        fertilizer_type: Global___FertilizerIrrigationData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fertilizer_type", b"fertilizer_type", "id", b"id", "type_detalis", b"type_detalis", "water_type", b"water_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fertilizer_type", b"fertilizer_type", "id", b"id", "is_on", b"is_on", "light", b"light", "type_detalis", b"type_detalis", "water_type", b"water_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_type_detalis: _TypeAlias = _typing.Literal["water_type", "fertilizer_type"]  # noqa: Y015
    _WhichOneofArgType_type_detalis: _TypeAlias = _typing.Literal["type_detalis", b"type_detalis"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type_detalis) -> _WhichOneofReturnType_type_detalis | None: ...

Global___IrrigationStatus: _TypeAlias = IrrigationStatus  # noqa: Y015

@_typing.final
class SetLightModeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    LIGHT_FIELD_NUMBER: _builtins.int
    light: Global___LightMode.ValueType
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        light: Global___LightMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "light", b"light"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetLightModeRequest: _TypeAlias = SetLightModeRequest  # noqa: Y015

@_typing.final
class SetWaterFlowRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    WATER_FLOW_FIELD_NUMBER: _builtins.int
    water_flow: _builtins.int
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        water_flow: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "water_flow", b"water_flow"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetWaterFlowRequest: _TypeAlias = SetWaterFlowRequest  # noqa: Y015

@_typing.final
class SetFertilizerRatioRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    FERTILIZER_RATIO_FIELD_NUMBER: _builtins.int
    fertilizer_ratio: _builtins.int
    @_builtins.property
    def id(self) -> _common_pb2.DeviceID: ...
    def __init__(
        self,
        *,
        id: _common_pb2.DeviceID | None = ...,
        fertilizer_ratio: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fertilizer_ratio", b"fertilizer_ratio", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetFertilizerRatioRequest: _TypeAlias = SetFertilizerRatioRequest  # noqa: Y015
