# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from laboratory import common_pb2 as laboratory_dot_common__pb2
from laboratory import irrigation_pb2 as laboratory_dot_irrigation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in laboratory/irrigation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IrrigationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIrrigationStatus = channel.unary_unary(
                '/laboratory.IrrigationService/GetIrrigationStatus',
                request_serializer=laboratory_dot_common__pb2.DeviceID.SerializeToString,
                response_deserializer=laboratory_dot_irrigation__pb2.IrrigationStatus.FromString,
                _registered_method=True)
        self.EnableIrrigation = channel.unary_unary(
                '/laboratory.IrrigationService/EnableIrrigation',
                request_serializer=laboratory_dot_common__pb2.DeviceID.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DisableIrrigation = channel.unary_unary(
                '/laboratory.IrrigationService/DisableIrrigation',
                request_serializer=laboratory_dot_common__pb2.DeviceID.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetLightMode = channel.unary_unary(
                '/laboratory.IrrigationService/SetLightMode',
                request_serializer=laboratory_dot_irrigation__pb2.SetLightModeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetWaterFlow = channel.unary_unary(
                '/laboratory.IrrigationService/SetWaterFlow',
                request_serializer=laboratory_dot_irrigation__pb2.SetWaterFlowRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetFertilizerRatio = channel.unary_unary(
                '/laboratory.IrrigationService/SetFertilizerRatio',
                request_serializer=laboratory_dot_irrigation__pb2.SetFertilizerRatioRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class IrrigationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIrrigationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableIrrigation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableIrrigation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLightMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWaterFlow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFertilizerRatio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IrrigationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIrrigationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIrrigationStatus,
                    request_deserializer=laboratory_dot_common__pb2.DeviceID.FromString,
                    response_serializer=laboratory_dot_irrigation__pb2.IrrigationStatus.SerializeToString,
            ),
            'EnableIrrigation': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableIrrigation,
                    request_deserializer=laboratory_dot_common__pb2.DeviceID.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DisableIrrigation': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableIrrigation,
                    request_deserializer=laboratory_dot_common__pb2.DeviceID.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetLightMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLightMode,
                    request_deserializer=laboratory_dot_irrigation__pb2.SetLightModeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetWaterFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWaterFlow,
                    request_deserializer=laboratory_dot_irrigation__pb2.SetWaterFlowRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetFertilizerRatio': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFertilizerRatio,
                    request_deserializer=laboratory_dot_irrigation__pb2.SetFertilizerRatioRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'laboratory.IrrigationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('laboratory.IrrigationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IrrigationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIrrigationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.IrrigationService/GetIrrigationStatus',
            laboratory_dot_common__pb2.DeviceID.SerializeToString,
            laboratory_dot_irrigation__pb2.IrrigationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableIrrigation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.IrrigationService/EnableIrrigation',
            laboratory_dot_common__pb2.DeviceID.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableIrrigation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.IrrigationService/DisableIrrigation',
            laboratory_dot_common__pb2.DeviceID.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLightMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.IrrigationService/SetLightMode',
            laboratory_dot_irrigation__pb2.SetLightModeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWaterFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.IrrigationService/SetWaterFlow',
            laboratory_dot_irrigation__pb2.SetWaterFlowRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFertilizerRatio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratory.IrrigationService/SetFertilizerRatio',
            laboratory_dot_irrigation__pb2.SetFertilizerRatioRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
