# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.10
#
# <auto-generated>
#
# Generated from file `Bank.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Bank
_M_Bank = Ice.openModule('Bank')
__name__ = 'Bank'

if 'Account' not in _M_Bank.__dict__:
    _M_Bank.Account = Ice.createTempClass()
    class Account(object):
        def __init__(self, owner='', balance=0):
            self.owner = owner
            self.balance = balance

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.owner)
            _h = 5 * _h + Ice.getHash(self.balance)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_Bank.Account):
                return NotImplemented
            else:
                if self.owner is None or other.owner is None:
                    if self.owner != other.owner:
                        return (-1 if self.owner is None else 1)
                else:
                    if self.owner < other.owner:
                        return -1
                    elif self.owner > other.owner:
                        return 1
                if self.balance is None or other.balance is None:
                    if self.balance != other.balance:
                        return (-1 if self.balance is None else 1)
                else:
                    if self.balance < other.balance:
                        return -1
                    elif self.balance > other.balance:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_Bank._t_Account)

        __repr__ = __str__

    _M_Bank._t_Account = IcePy.defineStruct('::Bank::Account', Account, (), (
        ('owner', (), IcePy._t_string),
        ('balance', (), IcePy._t_long)
    ))

    _M_Bank.Account = Account
    del Account

if '_t_Accounts' not in _M_Bank.__dict__:
    _M_Bank._t_Accounts = IcePy.defineSequence('::Bank::Accounts', (), _M_Bank._t_Account)

if 'AccountNotFound' not in _M_Bank.__dict__:
    _M_Bank.AccountNotFound = Ice.createTempClass()
    class AccountNotFound(Ice.UserException):
        def __init__(self, owner=''):
            self.owner = owner

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::Bank::AccountNotFound'

    _M_Bank._t_AccountNotFound = IcePy.defineException('::Bank::AccountNotFound', AccountNotFound, (), False, None, (('owner', (), IcePy._t_string, False, 0),))
    AccountNotFound._ice_type = _M_Bank._t_AccountNotFound

    _M_Bank.AccountNotFound = AccountNotFound
    del AccountNotFound

if 'AccountAlreadyExists' not in _M_Bank.__dict__:
    _M_Bank.AccountAlreadyExists = Ice.createTempClass()
    class AccountAlreadyExists(Ice.UserException):
        def __init__(self, owner=''):
            self.owner = owner

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::Bank::AccountAlreadyExists'

    _M_Bank._t_AccountAlreadyExists = IcePy.defineException('::Bank::AccountAlreadyExists', AccountAlreadyExists, (), False, None, (('owner', (), IcePy._t_string, False, 0),))
    AccountAlreadyExists._ice_type = _M_Bank._t_AccountAlreadyExists

    _M_Bank.AccountAlreadyExists = AccountAlreadyExists
    del AccountAlreadyExists

if 'InvalidAmount' not in _M_Bank.__dict__:
    _M_Bank.InvalidAmount = Ice.createTempClass()
    class InvalidAmount(Ice.UserException):
        def __init__(self, amount=0):
            self.amount = amount

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::Bank::InvalidAmount'

    _M_Bank._t_InvalidAmount = IcePy.defineException('::Bank::InvalidAmount', InvalidAmount, (), False, None, (('amount', (), IcePy._t_long, False, 0),))
    InvalidAmount._ice_type = _M_Bank._t_InvalidAmount

    _M_Bank.InvalidAmount = InvalidAmount
    del InvalidAmount

if 'InsufficientFunds' not in _M_Bank.__dict__:
    _M_Bank.InsufficientFunds = Ice.createTempClass()
    class InsufficientFunds(Ice.UserException):
        def __init__(self, owner='', amount=0, available=0):
            self.owner = owner
            self.amount = amount
            self.available = available

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::Bank::InsufficientFunds'

    _M_Bank._t_InsufficientFunds = IcePy.defineException('::Bank::InsufficientFunds', InsufficientFunds, (), False, None, (
        ('owner', (), IcePy._t_string, False, 0),
        ('amount', (), IcePy._t_long, False, 0),
        ('available', (), IcePy._t_long, False, 0)
    ))
    InsufficientFunds._ice_type = _M_Bank._t_InsufficientFunds

    _M_Bank.InsufficientFunds = InsufficientFunds
    del InsufficientFunds

_M_Bank._t_BankService = IcePy.defineValue('::Bank::BankService', Ice.Value, -1, (), False, True, None, ())

if 'BankServicePrx' not in _M_Bank.__dict__:
    _M_Bank.BankServicePrx = Ice.createTempClass()
    class BankServicePrx(Ice.ObjectPrx):

        def addAccount(self, owner, context=None):
            return _M_Bank.BankService._op_addAccount.invoke(self, ((owner, ), context))

        def addAccountAsync(self, owner, context=None):
            return _M_Bank.BankService._op_addAccount.invokeAsync(self, ((owner, ), context))

        def begin_addAccount(self, owner, _response=None, _ex=None, _sent=None, context=None):
            return _M_Bank.BankService._op_addAccount.begin(self, ((owner, ), _response, _ex, _sent, context))

        def end_addAccount(self, _r):
            return _M_Bank.BankService._op_addAccount.end(self, _r)

        def deleteAccount(self, owner, context=None):
            return _M_Bank.BankService._op_deleteAccount.invoke(self, ((owner, ), context))

        def deleteAccountAsync(self, owner, context=None):
            return _M_Bank.BankService._op_deleteAccount.invokeAsync(self, ((owner, ), context))

        def begin_deleteAccount(self, owner, _response=None, _ex=None, _sent=None, context=None):
            return _M_Bank.BankService._op_deleteAccount.begin(self, ((owner, ), _response, _ex, _sent, context))

        def end_deleteAccount(self, _r):
            return _M_Bank.BankService._op_deleteAccount.end(self, _r)

        def deposit(self, owner, amount, context=None):
            return _M_Bank.BankService._op_deposit.invoke(self, ((owner, amount), context))

        def depositAsync(self, owner, amount, context=None):
            return _M_Bank.BankService._op_deposit.invokeAsync(self, ((owner, amount), context))

        def begin_deposit(self, owner, amount, _response=None, _ex=None, _sent=None, context=None):
            return _M_Bank.BankService._op_deposit.begin(self, ((owner, amount), _response, _ex, _sent, context))

        def end_deposit(self, _r):
            return _M_Bank.BankService._op_deposit.end(self, _r)

        def withdraw(self, owner, amount, context=None):
            return _M_Bank.BankService._op_withdraw.invoke(self, ((owner, amount), context))

        def withdrawAsync(self, owner, amount, context=None):
            return _M_Bank.BankService._op_withdraw.invokeAsync(self, ((owner, amount), context))

        def begin_withdraw(self, owner, amount, _response=None, _ex=None, _sent=None, context=None):
            return _M_Bank.BankService._op_withdraw.begin(self, ((owner, amount), _response, _ex, _sent, context))

        def end_withdraw(self, _r):
            return _M_Bank.BankService._op_withdraw.end(self, _r)

        def getBalance(self, owner, context=None):
            return _M_Bank.BankService._op_getBalance.invoke(self, ((owner, ), context))

        def getBalanceAsync(self, owner, context=None):
            return _M_Bank.BankService._op_getBalance.invokeAsync(self, ((owner, ), context))

        def begin_getBalance(self, owner, _response=None, _ex=None, _sent=None, context=None):
            return _M_Bank.BankService._op_getBalance.begin(self, ((owner, ), _response, _ex, _sent, context))

        def end_getBalance(self, _r):
            return _M_Bank.BankService._op_getBalance.end(self, _r)

        def listAccounts(self, context=None):
            return _M_Bank.BankService._op_listAccounts.invoke(self, ((), context))

        def listAccountsAsync(self, context=None):
            return _M_Bank.BankService._op_listAccounts.invokeAsync(self, ((), context))

        def begin_listAccounts(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_Bank.BankService._op_listAccounts.begin(self, ((), _response, _ex, _sent, context))

        def end_listAccounts(self, _r):
            return _M_Bank.BankService._op_listAccounts.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Bank.BankServicePrx.ice_checkedCast(proxy, '::Bank::BankService', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Bank.BankServicePrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Bank::BankService'
    _M_Bank._t_BankServicePrx = IcePy.defineProxy('::Bank::BankService', BankServicePrx)

    _M_Bank.BankServicePrx = BankServicePrx
    del BankServicePrx

    _M_Bank.BankService = Ice.createTempClass()
    class BankService(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Bank::BankService', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Bank::BankService'

        @staticmethod
        def ice_staticId():
            return '::Bank::BankService'

        def addAccount(self, owner, current=None):
            raise NotImplementedError("servant method 'addAccount' not implemented")

        def deleteAccount(self, owner, current=None):
            raise NotImplementedError("servant method 'deleteAccount' not implemented")

        def deposit(self, owner, amount, current=None):
            raise NotImplementedError("servant method 'deposit' not implemented")

        def withdraw(self, owner, amount, current=None):
            raise NotImplementedError("servant method 'withdraw' not implemented")

        def getBalance(self, owner, current=None):
            raise NotImplementedError("servant method 'getBalance' not implemented")

        def listAccounts(self, current=None):
            raise NotImplementedError("servant method 'listAccounts' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Bank._t_BankServiceDisp)

        __repr__ = __str__

    _M_Bank._t_BankServiceDisp = IcePy.defineClass('::Bank::BankService', BankService, (), None, ())
    BankService._ice_type = _M_Bank._t_BankServiceDisp

    BankService._op_addAccount = IcePy.Operation('addAccount', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), None, (_M_Bank._t_AccountAlreadyExists,))
    BankService._op_deleteAccount = IcePy.Operation('deleteAccount', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), None, (_M_Bank._t_AccountNotFound,))
    BankService._op_deposit = IcePy.Operation('deposit', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), None, (_M_Bank._t_AccountNotFound, _M_Bank._t_InvalidAmount))
    BankService._op_withdraw = IcePy.Operation('withdraw', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (), None, (_M_Bank._t_AccountNotFound, _M_Bank._t_InvalidAmount, _M_Bank._t_InsufficientFunds))
    BankService._op_getBalance = IcePy.Operation('getBalance', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_long, False, 0), (_M_Bank._t_AccountNotFound,))
    BankService._op_listAccounts = IcePy.Operation('listAccounts', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), _M_Bank._t_Accounts, False, 0), ())

    _M_Bank.BankService = BankService
    del BankService

# End of module Bank
